### ISSUE TITLE
Negative action filter to remove certain action from the result

### ISSUE THREAD

**Issue by chuan137** [sapcc/hermescli#8]
The use case is for manila service. Whenever a user visits the "Shared File System Storage" page, an action of "update/access_list" is triggered for every share. For a large projects with many shares, this type of action dominates the result and they are not very interesting.

So it would be nice to be able to pass a string starting with a special char to the `--action` flag , for example "!", then I could do  `--action !update/access_list`.

**Comment by kayrus** [comment]
@chuan137  depends on https://github.com/sapcc/hermes/issues/36

**Comment by notque** [comment]
Should access list even be recorded? We don't record any other read or access level events

**Comment by chuan137** [comment]
the update/access_list is still an update event, the access_list refers to the export locations of the NFS share

**Comment by notque** [comment]
this was added awhile ago, i just noticed I didn't update the issue. GET /v1/events?outcome=!failed
